[build]
  base = "frontend/"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://your-backend-app.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200